import struct
import serial
import csv
import sys
import glob
import time
import os

# --- IMPORT CONFIGURATION ---
try:
    # This file is auto-generated by tools/gen_sensors.py
    import sensor_config as cfg
except ImportError:
    print("Error: 'sensor_config.py' not found.")
    print("Did you run './tools/deploy_rockchip.sh'?")
    sys.exit(1)

# --- CONFIG ---
# Determine the absolute path to this script's directory
# This ensures the CSV is found regardless of where you run the command from
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
CSV_FILE = os.path.join(SCRIPT_DIR, 'phoenix_sensor_stream.csv')

BAUD_RATE = 1000000 
SYNC = b'\xAA\xBB'
REQ_CMD = b'\xDE\xAD\xBE\xEF'

def find_pico_port():
    # Try the specific UDEV rule first
    ports = glob.glob('/dev/ttyHIL')
    if not ports:
        # Fallback to standard ACM ports if the rule isn't active
        ports = glob.glob('/dev/ttyACM*')
    
    if not ports:
        print("Error: No Pico found (checked /dev/ttyHIL and /dev/ttyACM*).")
        sys.exit(1)
        
    print(f"Found Pico at: {ports[0]}")
    return ports[0]

def load_csv(filename):
    print(f"Loading {filename}...")
    data = []
    try:
        with open(filename, 'r') as f:
            reader = csv.DictReader(f)
            # Clean up headers (strip spaces)
            reader.fieldnames = [name.strip() for name in reader.fieldnames]
            for row in reader:
                data.append(row)
    except FileNotFoundError:
        print(f"Error: CSV file not found at {filename}")
        sys.exit(1)
    print(f"Loaded {len(data)} rows.")
    return data

def run():
    rows = load_csv(CSV_FILE)
    total_rows = len(rows)
    row_idx = 0
    
    port = find_pico_port()
    print(f"Connecting to {port}...")
    
    try:
        ser = serial.Serial(port, BAUD_RATE, timeout=0.01)
    except Exception as e:
        print(f"Serial Error: {e}")
        sys.exit(1)

    print("Connected. Waiting for 'DEADBEEF' requests...")

    # Sequence counters (0-65535)
    seq_imu = 0
    seq_baro = 0
    seq_gps = 0

    while True:
        try:
            if ser.in_waiting > 0:
                raw_data = ser.read(ser.in_waiting)

                # 1. CHECK FOR REQUEST COMMAND
                if REQ_CMD in raw_data:
                    batch_buffer = bytearray()
                    
                    # Generate a batch (e.g. 100 samples) to send back
                    for _ in range(100):
                        row = rows[row_idx]
                        t_ms = seq_imu # Using sequence as a simple timestamp proxy

                        # --- 1. IMU PACKET (1kHz) ---
                        # Source: SI Units (m/s^2)
                        accel_si = float(row['accel_x']) 
                        
                        # Apply Generated Sensitivity (SI -> Raw)
                        raw_accel = int(accel_si / cfg.IMU_ACCEL_SENSITIVITY)
                        
                        # Clamp to 16-bit signed integer range
                        raw_accel = max(-32768, min(32767, raw_accel))

                        # Packet: [Seq(2), Time(4), AccelX(2)]
                        # Note: We use 'h' (short) for 16-bit signed
                        payload = struct.pack('<H I h', seq_imu, t_ms, raw_accel)
                        # Protocol: [Sync(2), Type(1), Payload(N), CRC(1)]
                        pkt = struct.pack('<2s B', SYNC, 0x01) + payload + b'\x00' 
                        batch_buffer.extend(pkt)
                        
                        seq_imu = (seq_imu + 1) % 65535

                        # --- 2. BARO PACKET (50Hz - every 20th IMU tick) ---
                        if seq_imu % 20 == 0: 
                            # Source: Pascals (Pa)
                            pres_pa = float(row['pressure_pa'])
                            
                            # Apply Sensitivity (Handles scaling automatically)
                            raw_pres = int(pres_pa / cfg.BMP581_SENSITIVITY)
                            
                            # Packet: [Seq(2), Time(4), Pressure(4)]
                            payload = struct.pack('<H I i', seq_baro, t_ms, raw_pres) 
                            pkt = struct.pack('<2s B', SYNC, 0x02) + payload + b'\x00'
                            batch_buffer.extend(pkt)
                            seq_baro = (seq_baro + 1) % 65535

                        # --- 3. GPS PACKET (10Hz - every 100th IMU tick) ---
                        if seq_imu % 100 == 0:
                            # Source: Degrees
                            lat_deg = float(row['lat'])
                            
                            # Apply Sensitivity (Handles 1e7 scaling automatically)
                            raw_lat = int(lat_deg / cfg.GPS_SENSITIVITY)
                            
                            # Packet: [Seq(2), Time(4), Lat(4)]
                            payload = struct.pack('<H I i', seq_gps, t_ms, raw_lat)
                            pkt = struct.pack('<2s B', SYNC, 0x03) + payload + b'\x00'
                            batch_buffer.extend(pkt)
                            seq_gps = (seq_gps + 1) % 65535
                        
                        # Advance CSV index
                        row_idx = (row_idx + 1) % total_rows

                    # Send the full batch at once
                    ser.write(batch_buffer)
                    
                    # Clear processed command from buffer
                    raw_data = raw_data.replace(REQ_CMD, b'')

                # 2. LOGGING (Print Debug msgs from Pico)
                if raw_data:
                    try:
                        text = raw_data.decode('utf-8', errors='ignore')
                        # Only print lines marked with [HIL] to reduce noise
                        if "[HIL]" in text: 
                            print(text.strip())
                    except: pass

        except KeyboardInterrupt:
            print("\nStopping Streamer...")
            break
        except Exception as e:
            print(f"\nRuntime Error: {e}")
            break

if __name__ == "__main__":
    run()