#!/usr/bin/env python3
from __future__ import annotations
"""
generate_norb_topics.py — nORB message code generator
======================================================
Reads .msg topic definition files and emits:
  - norb/topic_defs/<topic>.h   — per-topic struct (or extern-type alias)
  - norb/topics.h               — topic_id_t enum (replaces hand-written version)
  - norb_autogen.c              — queue creation; norb.c calls norb_autogen_init_queues()

Usage (called by CMake add_custom_command):
  python3 generate_norb_topics.py --outdir <build_dir>/norb_generated \
      --topics msg/sensor_imu.msg msg/vehicle_state.msg ...

.msg File Format:
  # Comments begin with '#'.
  # Blank lines are ignored.

  Primitive field (scalar):
      float  temperature_c     # optional comment

  Primitive field (fixed-length array):
      float[3]  accel_ms2      # optional comment
      uint64_t[2]  timestamps

  Supported primitive types:
      uint8_t uint16_t uint32_t uint64_t
      int8_t  int16_t  int32_t  int64_t
      float   double   bool     char

  External/ICD type (opaque wrapper — no struct fields generated):
      @include <phoenix_icd.h>
      @extern TlmIdentificationPayload_t

  Only ONE @extern per file. @extern topics alias the external type rather
  than generating a new struct, keeping sizeof() and casts correct.
"""

import argparse
import os
import re
import sys
from pathlib import Path
from datetime import datetime, timezone

# ── Supported primitive types ─────────────────────────────────────────────────
PRIMITIVE_TYPES = {
    "uint8_t", "uint16_t", "uint32_t", "uint64_t",
    "int8_t",  "int16_t",  "int32_t",  "int64_t",
    "float", "double", "bool", "char",
}

BANNER = """\
/* =============================================================================
 * AUTO-GENERATED FILE — DO NOT EDIT
 * Generated by: tools/generate_norb_topics.py
 * Generated on: {date}
 *
 * To change this file, edit the .msg source in msg/ and rebuild.
 * ============================================================================= */
"""

# ── Parser ────────────────────────────────────────────────────────────────────

class MsgField:
    """Represents a single field inside a .msg file."""
    def __init__(self, base_type: str, name: str, array_size: int | None, comment: str):
        self.base_type  = base_type    # e.g. "float"
        self.name       = name         # e.g. "accel_ms2"
        self.array_size = array_size   # None for scalar, int for array
        self.comment    = comment      # trailing comment text (may be empty)

    def c_declaration(self) -> str:
        if self.array_size is not None:
            return f"{self.base_type} {self.name}[{self.array_size}]"
        return f"{self.base_type} {self.name}"


class MsgTopic:
    """Parsed representation of a single .msg file."""
    def __init__(self, name: str):
        self.name      = name          # e.g. "sensor_imu"
        self.fields: list[MsgField] = []
        self.includes: list[str] = []  # from @include directives
        self.extern_type: str | None = None  # from @extern directive
        self.file_comments: list[str] = []   # leading # comment lines

    @property
    def topic_id(self) -> str:
        """TOPIC_SENSOR_IMU"""
        return f"TOPIC_{self.name.upper()}"

    @property
    def struct_type(self) -> str:
        """sensor_imu_t"""
        return f"{self.name}_t"

    @property
    def is_extern(self) -> bool:
        return self.extern_type is not None


def parse_msg_file(path: Path) -> MsgTopic:
    topic_name = path.stem          # "sensor_imu" from "sensor_imu.msg"
    topic = MsgTopic(topic_name)

    # Regex for optional array specifier on the type: float[3] or float
    field_re = re.compile(
        r"^(?P<type>\w+)(?:\[(?P<size>\d+)\])?\s+(?P<name>\w+)"
        r"(?:\s*#\s*(?P<comment>.*))?$"
    )

    with open(path) as f:
        for raw_line in f:
            line = raw_line.rstrip()
            stripped = line.strip()

            if not stripped:
                continue

            # Leading file-level comments (before any directives/fields)
            if stripped.startswith("#"):
                if not topic.fields and not topic.includes and topic.extern_type is None:
                    comment_text = stripped.lstrip("#").strip()
                    if comment_text:
                        topic.file_comments.append(comment_text)
                continue

            # @include directive
            if stripped.startswith("@include"):
                rest = stripped[len("@include"):].strip()
                topic.includes.append(rest)
                continue

            # @extern directive
            if stripped.startswith("@extern"):
                extern_type = stripped[len("@extern"):].strip()
                if not extern_type:
                    sys.exit(f"ERROR: {path}: @extern is missing the type name")
                if topic.fields:
                    sys.exit(f"ERROR: {path}: @extern cannot be mixed with field declarations")
                topic.extern_type = extern_type
                continue

            # Inline comment on a field line
            m = field_re.match(stripped)
            if m:
                base_type  = m.group("type")
                array_size = int(m.group("size")) if m.group("size") else None
                field_name = m.group("name")
                comment    = (m.group("comment") or "").strip()

                if base_type not in PRIMITIVE_TYPES:
                    sys.exit(
                        f"ERROR: {path}: unknown type '{base_type}'.\n"
                        f"  Supported: {', '.join(sorted(PRIMITIVE_TYPES))}\n"
                        f"  For external types, use '@extern TypeName' instead of declaring fields."
                    )
                if topic.extern_type is not None:
                    sys.exit(f"ERROR: {path}: cannot declare fields after @extern")

                topic.fields.append(MsgField(base_type, field_name, array_size, comment))
                continue

            sys.exit(f"ERROR: {path}: unrecognised line: {repr(stripped)}")

    if not topic.fields and topic.extern_type is None:
        sys.exit(f"ERROR: {path}: no fields or @extern found — file is empty or invalid")

    return topic


# ── Code generators ───────────────────────────────────────────────────────────

def banner() -> str:
    return BANNER.format(date=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"))


def generate_topic_header(topic: MsgTopic) -> str:
    """Emit the per-topic header file content."""
    lines: list[str] = []
    lines.append(banner())

    guard = f"NORB_TOPIC_{topic.name.upper()}_H"
    lines.append(f"#ifndef {guard}")
    lines.append(f"#define {guard}")
    lines.append("")

    if topic.file_comments:
        lines.append("/**")
        for c in topic.file_comments:
            lines.append(f" * {c}")
        lines.append(" */")
        lines.append("")

    if topic.is_extern:
        # Just pull in the external header and create a convenience alias
        for inc in topic.includes:
            lines.append(f"#include {inc}")
        lines.append("")
        lines.append(f"/* Convenience alias — code may use either name */")
        lines.append(f"typedef {topic.extern_type} {topic.struct_type};")
    else:
        # Always need stdint / stdbool for primitive types
        lines.append("#include <stdint.h>")
        lines.append("#include <stdbool.h>")
        for inc in topic.includes:
            lines.append(f"#include {inc}")
        lines.append("")
        lines.append(f"typedef struct {{")

        # Calculate column alignment for field names
        decls = [f.c_declaration() for f in topic.fields]
        max_decl_len = max(len(d) for d in decls) if decls else 0

        for field, decl in zip(topic.fields, decls):
            padding = " " * (max_decl_len - len(decl) + 1)
            if field.comment:
                lines.append(f"    {decl};{padding}/* {field.comment} */")
            else:
                lines.append(f"    {decl};")

        lines.append(f"}} {topic.struct_type};")

    lines.append("")
    lines.append(f"#endif /* {guard} */")
    lines.append("")
    return "\n".join(lines)


def generate_topics_enum(topics: list[MsgTopic]) -> str:
    """Emit norb/topics.h — the topic_id_t enum."""
    lines: list[str] = []
    lines.append(banner())
    lines.append("#ifndef NORB_TOPICS_H")
    lines.append("#define NORB_TOPICS_H")
    lines.append("")
    lines.append("typedef enum {")

    for topic in topics:
        lines.append(f"    {topic.topic_id},")

    lines.append("")
    lines.append("    TOPIC_COUNT   /* always last — sizes the queue array */")
    lines.append("} topic_id_t;")
    lines.append("")
    lines.append("#endif /* NORB_TOPICS_H */")
    lines.append("")
    return "\n".join(lines)


def generate_autogen_c(topics: list[MsgTopic]) -> str:
    """Emit norb_autogen.c — FreeRTOS queue creation, called from norb_init()."""
    lines: list[str] = []
    lines.append(banner())
    lines.append("/* This file is compiled into the firmware alongside norb.c.        */")
    lines.append("/* norb_autogen_init_queues() is called once by norb_init().        */")
    lines.append("")
    lines.append("#include <FreeRTOS.h>")
    lines.append("#include <queue.h>")
    lines.append("")
    lines.append('/* Generated topic headers */')
    for topic in topics:
        lines.append(f'#include "norb/topic_defs/{topic.name}.h"')
    lines.append("")
    lines.append('/* Generated enum (topic_id_t + TOPIC_COUNT) */')
    lines.append('#include "norb/topics.h"')
    lines.append("")
    lines.append("/* Static memory for each topic queue (no dynamic allocation) */")
    for topic in topics:
        lines.append(f"static StaticQueue_t _norb_qbuf_{topic.name};")
        lines.append(f"static uint8_t       _norb_qstorage_{topic.name}[sizeof({topic.struct_type})];")
    lines.append("")
    lines.append("/**")
    lines.append(" * @brief Populate the topic queue array.")
    lines.append(" *")
    lines.append(" * Called once by norb_init() before the scheduler starts.")
    lines.append(" * Do NOT call this from more than one place.")
    lines.append(" *")
    lines.append(" * @param queues  Pointer to the static QueueHandle_t array of size TOPIC_COUNT.")
    lines.append(" */")
    lines.append("void norb_autogen_init_queues(QueueHandle_t *queues) {")

    for topic in topics:
        lines.append(
            f"    queues[{topic.topic_id}] = xQueueCreateStatic("
            f"1, sizeof({topic.struct_type}), "
            f"_norb_qstorage_{topic.name}, &_norb_qbuf_{topic.name});"
        )

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


# ── Entry point ───────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="nORB topic code generator")
    parser.add_argument(
        "--outdir", required=True,
        help="Output directory for generated files (e.g. build/norb_generated)"
    )
    parser.add_argument(
        "--topics", nargs="+", required=True,
        help="List of .msg files to process"
    )
    args = parser.parse_args()

    out_root   = Path(args.outdir)
    topic_defs = out_root / "norb" / "topic_defs"
    topic_defs.mkdir(parents=True, exist_ok=True)

    # 1 ── Parse every .msg file ───────────────────────────────────────────────
    topics: list[MsgTopic] = []
    for msg_path_str in args.topics:
        msg_path = Path(msg_path_str)
        if not msg_path.exists():
            sys.exit(f"ERROR: .msg file not found: {msg_path}")
        topics.append(parse_msg_file(msg_path))

    print(f"[norb_gen] Processing {len(topics)} topic(s): "
          f"{', '.join(t.name for t in topics)}")

    # 2 ── Per-topic headers ───────────────────────────────────────────────────
    for topic in topics:
        header_path = topic_defs / f"{topic.name}.h"
        header_path.write_text(generate_topic_header(topic))
        print(f"[norb_gen]   wrote {header_path.relative_to(out_root)}")

    # 3 ── norb/topics.h ───────────────────────────────────────────────────────
    (out_root / "norb").mkdir(parents=True, exist_ok=True)
    topics_h = out_root / "norb" / "topics.h"
    topics_h.write_text(generate_topics_enum(topics))
    print(f"[norb_gen]   wrote {topics_h.relative_to(out_root)}")

    # 4 ── norb_autogen.c ──────────────────────────────────────────────────────
    autogen_c = out_root / "norb_autogen.c"
    autogen_c.write_text(generate_autogen_c(topics))
    print(f"[norb_gen]   wrote {autogen_c.relative_to(out_root)}")

    print(f"[norb_gen] Done. Output in: {out_root}")


if __name__ == "__main__":
    main()
