# AUTO-GENERATED — DO NOT EDIT
# Generated by: tools/generate_norb_topics.py
# Re-run CMake build to regenerate after adding/changing .msg files.

import struct
from typing import Any, Dict

TOPIC_BAROMETER = 0
TOPIC_EPS_IDENT = 1
TOPIC_EPS_MEASUREMENTS = 2
TOPIC_EPS_POWER_STATUS = 3
TOPIC_OBC_IDENT = 4
TOPIC_OBC_LOG_LEVEL = 5
TOPIC_SENSOR_IMU = 6
TOPIC_TRACKING_RADIO_IDENT = 7
TOPIC_VEHICLE_IMU = 8
TOPIC_VEHICLE_STATE = 9

TOPIC_NAMES: Dict[int, str] = {
    0: 'BAROMETER',
    1: 'EPS_IDENT',
    2: 'EPS_MEASUREMENTS',
    3: 'EPS_POWER_STATUS',
    4: 'OBC_IDENT',
    5: 'OBC_LOG_LEVEL',
    6: 'SENSOR_IMU',
    7: 'TRACKING_RADIO_IDENT',
    8: 'VEHICLE_IMU',
    9: 'VEHICLE_STATE',
}

def unpack_barometer(raw: bytes) -> Dict[str, Any]:
    """Unpack EVENT_OBC_NORB_STREAM payload for topic BAROMETER.
    raw = payload[1:] (strips the leading topic_id byte).
    Byte layout: [uint32 timestamp_ms][barometer_t fields...]
    """
    unpacked = struct.unpack_from('<IQfff', raw)
    return {
        'timestamp_ms': unpacked[0],
        'timestamp_us': unpacked[1],
        'pressure_pa': unpacked[2],
        'temperature_c': unpacked[3],
        'altitude_m': unpacked[4],
    }

def unpack_eps_ident(raw: bytes) -> Dict[str, Any]:
    """Unpack EVENT_OBC_NORB_STREAM payload for topic EPS_IDENT.
    raw = payload[1:] (strips the leading topic_id byte).
    Byte layout: [uint32 timestamp_ms][eps_ident_t fields...]
    """
    unpacked = struct.unpack_from('<IBBBBHH', raw)
    return {
        'timestamp_ms': unpacked[0],
        'node_type': unpacked[1],
        'interface_version': unpacked[2],
        'firmware_major': unpacked[3],
        'firmware_minor': unpacked[4],
        'uptime_seconds': unpacked[5],
        'uptime_milliseconds': unpacked[6],
    }

def unpack_eps_measurements(raw: bytes) -> Dict[str, Any]:
    """Unpack EVENT_OBC_NORB_STREAM payload for topic EPS_MEASUREMENTS.
    raw = payload[1:] (strips the leading topic_id byte).
    Byte layout: [uint32 timestamp_ms][eps_measurements_t fields...]
    """
    unpacked = struct.unpack_from('<IHHHHH', raw)
    return {
        'timestamp_ms': unpacked[0],
        'batt_voltage_mv': unpacked[1],
        'batt_current_ma': unpacked[2],
        'current_3v3_1_ma': unpacked[3],
        'current_5v_1_ma': unpacked[4],
        'current_12v_ma': unpacked[5],
    }

def unpack_eps_power_status(raw: bytes) -> Dict[str, Any]:
    """Unpack EVENT_OBC_NORB_STREAM payload for topic EPS_POWER_STATUS.
    raw = payload[1:] (strips the leading topic_id byte).
    Byte layout: [uint32 timestamp_ms][eps_power_status_t fields...]
    """
    # Bitfield struct EpsPowerStatus_t: cannot use struct.unpack directly.
    # Returns raw bytes for manual interpretation.
    ts_ms = struct.unpack_from('<I', raw)[0]
    return {'timestamp_ms': ts_ms, 'raw_data': list(raw[4:])}

def unpack_obc_ident(raw: bytes) -> Dict[str, Any]:
    """Unpack EVENT_OBC_NORB_STREAM payload for topic OBC_IDENT.
    raw = payload[1:] (strips the leading topic_id byte).
    Byte layout: [uint32 timestamp_ms][obc_ident_t fields...]
    """
    unpacked = struct.unpack_from('<IBBBBHH', raw)
    return {
        'timestamp_ms': unpacked[0],
        'node_type': unpacked[1],
        'interface_version': unpacked[2],
        'firmware_major': unpacked[3],
        'firmware_minor': unpacked[4],
        'uptime_seconds': unpacked[5],
        'uptime_milliseconds': unpacked[6],
    }

def unpack_obc_log_level(raw: bytes) -> Dict[str, Any]:
    """Unpack EVENT_OBC_NORB_STREAM payload for topic OBC_LOG_LEVEL.
    raw = payload[1:] (strips the leading topic_id byte).
    Byte layout: [uint32 timestamp_ms][obc_log_level_t fields...]
    """
    # Bitfield struct EventLogConfig_t: cannot use struct.unpack directly.
    # Returns raw bytes for manual interpretation.
    ts_ms = struct.unpack_from('<I', raw)[0]
    return {'timestamp_ms': ts_ms, 'raw_data': list(raw[4:])}

def unpack_sensor_imu(raw: bytes) -> Dict[str, Any]:
    """Unpack EVENT_OBC_NORB_STREAM payload for topic SENSOR_IMU.
    raw = payload[1:] (strips the leading topic_id byte).
    Byte layout: [uint32 timestamp_ms][sensor_imu_t fields...]
    """
    unpacked = struct.unpack_from('<IQ3f3ff', raw)
    return {
        'timestamp_ms': unpacked[0],
        'timestamp_us': unpacked[1],
        'accel_ms2': list(unpacked[2:5]),
        'gyro_rads': list(unpacked[5:8]),
        'temperature_c': unpacked[8],
    }

def unpack_tracking_radio_ident(raw: bytes) -> Dict[str, Any]:
    """Unpack EVENT_OBC_NORB_STREAM payload for topic TRACKING_RADIO_IDENT.
    raw = payload[1:] (strips the leading topic_id byte).
    Byte layout: [uint32 timestamp_ms][tracking_radio_ident_t fields...]
    """
    unpacked = struct.unpack_from('<IBBBBHH', raw)
    return {
        'timestamp_ms': unpacked[0],
        'node_type': unpacked[1],
        'interface_version': unpacked[2],
        'firmware_major': unpacked[3],
        'firmware_minor': unpacked[4],
        'uptime_seconds': unpacked[5],
        'uptime_milliseconds': unpacked[6],
    }

def unpack_vehicle_imu(raw: bytes) -> Dict[str, Any]:
    """Unpack EVENT_OBC_NORB_STREAM payload for topic VEHICLE_IMU.
    raw = payload[1:] (strips the leading topic_id byte).
    Byte layout: [uint32 timestamp_ms][vehicle_imu_t fields...]
    """
    unpacked = struct.unpack_from('<IQ3f3ff', raw)
    return {
        'timestamp_ms': unpacked[0],
        'timestamp_us': unpacked[1],
        'delta_angle': list(unpacked[2:5]),
        'delta_velocity': list(unpacked[5:8]),
        'dt_s': unpacked[8],
    }

def unpack_vehicle_state(raw: bytes) -> Dict[str, Any]:
    """Unpack EVENT_OBC_NORB_STREAM payload for topic VEHICLE_STATE.
    raw = payload[1:] (strips the leading topic_id byte).
    Byte layout: [uint32 timestamp_ms][vehicle_state_t fields...]
    """
    unpacked = struct.unpack_from('<IQ4f3f3f3f3ff', raw)
    return {
        'timestamp_ms': unpacked[0],
        'timestamp_us': unpacked[1],
        'quaternion': list(unpacked[2:6]),
        'velocity_ms': list(unpacked[6:9]),
        'position_m': list(unpacked[9:12]),
        'accel_bias_ms2': list(unpacked[12:15]),
        'gyro_bias_rads': list(unpacked[15:18]),
        'altitude_m': unpacked[18],
    }

# Map topic_id integer → unpack function.
# Usage: parsed = UNPACK_FNS[topic_id](payload[1:])
UNPACK_FNS: Dict[int, Any] = {
    0: unpack_barometer,
    1: unpack_eps_ident,
    2: unpack_eps_measurements,
    3: unpack_eps_power_status,
    4: unpack_obc_ident,
    5: unpack_obc_log_level,
    6: unpack_sensor_imu,
    7: unpack_tracking_radio_ident,
    8: unpack_vehicle_imu,
    9: unpack_vehicle_state,
}
